# Generated by Django 5.1.5 on 2025-02-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_rename_catrgory_books_category_alter_books_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='total_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
